; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = ./**/*platformio.ini

[env]
lib_deps = 
	waspinator/AccelStepper @ 1.61
	https://github.com/MobiFlight/LiquidCrystal_I2C#v1.1.4
	https://github.com/MobiFlight/Arduino-CmdMessenger#4.2.1
	chris--a/Keypad @ ^3.1.1
custom_lib_deps_atmel = 
	arduino-libraries/Servo @ 1.1.8
custom_lib_deps_pico = 
	ricaun/ArduinoUniqueID @ ^1.3.0
build_flags = 
	-DMF_REDUCE_FUNCT_LEDCONTROL
	-DMAXCALLBACKS=35
	-DSERIAL_RX_BUFFER_SIZE=96
	-DMESSENGERBUFFERSIZE=96
	-DMAXSTREAMBUFFERSIZE=96
	-DDEFAULT_TIMEOUT=5000
	-DMF_SEGMENT_SUPPORT
	-DMF_LCD_SUPPORT
	-DMF_STEPPER_SUPPORT
	-DMF_SERVO_SUPPORT
	-DMF_ANALOG_SUPPORT
	-DMF_OUTPUT_SHIFTER_SUPPORT
	-DMF_INPUT_SHIFTER_SUPPORT
	-DMF_MUX_SUPPORT
	-DMF_MUX_SUPPORT
	-DMF_DIGIN_MUX_SUPPORT
	-I./src/src
	-I./src/src/MF_Analog
	-I./src/src/MF_Button
	-I./src/src/MF_Encoder
	-I./src/src/MF_InputShifter
	-I./src/src/MF_DigInMux
	-I./src/src/MF_LCDDisplay
	-I./src/src/MF_Output
	-I./src/src/MF_OutputShifter
	-I./src/src/MF_Segment
	-I./src/src/MF_Servo
	-I./src/src/MF_Stepper
	-I./src/src/MF_Modules
build_src_filter = 
	+<*>
extra_scripts = 
	pre:get_version.py
	pre:get_CoreFiles.py
	copy_fw_files.py

[env_KeypadVA]
build_flags = 
	${env.build_flags}
	-DMF_CUSTOMDEVICE_SUPPORT=1
	-I./src/src/MF_CustomDevice
	-I./KeypadVA
build_src_filter = 
	+<../KeypadVA>
lib_deps = 
custom_core_firmware_version = 3.0.0
custom_source_folder = KeypadVA
custom_community_project = Feurer_KeypadVA
custom_zip_filename = ${env_KeypadVA.custom_community_project}

[env:feurer_keypadva_mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags = 
	${env_KeypadVA.build_flags}
	'-DMOBIFLIGHT_TYPE="Feurer KeypadVA Mega"'
	'-DMOBIFLIGHT_NAME="Feurer KeypadVA"'
	-DMEMLEN_CONFIG=1496
	-DMEMLEN_NAMES_BUFFER=1000
	-DMF_MAX_DEVICEMEM=1600
build_unflags = 
build_src_filter = 
	${env.build_src_filter}
	${env_KeypadVA.build_src_filter}
lib_deps = 
	${env.lib_deps}
	${env.custom_lib_deps_Atmel}
	${env_KeypadVA.lib_deps}
monitor_speed = 115200
extra_scripts = 
	${env.extra_scripts}
custom_core_firmware_version = ${env_KeypadVA.custom_core_firmware_version}
custom_community_project = ${env_KeypadVA.custom_community_project}
custom_source_folder = ${env_KeypadVA.custom_source_folder}
custom_zip_filename = ${env_KeypadVA.custom_zip_filename}

[env:feurer_keypadva_micro]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino
build_flags = 
	${env_KeypadVA.build_flags}
	'-DMOBIFLIGHT_TYPE="Feurer KeypadVA Micro"'
	'-DMOBIFLIGHT_NAME="Feurer KeypadVA"'
	-DMEMLEN_CONFIG=440
	-DMEMLEN_NAMES_BUFFER=350
	-DMF_MAX_DEVICEMEM=470
build_unflags = 
	-DMF_STEPPER_SUPPORT
build_src_filter = 
	${env.build_src_filter}
	${env_KeypadVA.build_src_filter}
lib_deps = 
	${env.lib_deps}
	${env.custom_lib_deps_Atmel}
	${env_KeypadVA.lib_deps}
monitor_speed = 115200
extra_scripts = 
	${env.extra_scripts}
custom_core_firmware_version = ${env_KeypadVA.custom_core_firmware_version}
custom_community_project = ${env_KeypadVA.custom_community_project}
custom_source_folder = ${env_KeypadVA.custom_source_folder}
custom_zip_filename = ${env_KeypadVA.custom_zip_filename}

[env:feurer_keypadva_uno]
platform = atmelavr
board = uno
framework = arduino
build_flags = 
	${env_KeypadVA.build_flags}
	'-DMOBIFLIGHT_TYPE="Feurer KeypadVA Uno"'
	'-DMOBIFLIGHT_NAME="Feurer KeypadVA"'
	-DMEMLEN_CONFIG=286
	-DMEMLEN_NAMES_BUFFER=220
	-DMF_MAX_DEVICEMEM=420
build_unflags = 
build_src_filter = 
	${env.build_src_filter}
	${env_KeypadVA.build_src_filter}
lib_deps = 
	${env.lib_deps}
	${env.custom_lib_deps_Atmel}
	${env_KeypadVA.lib_deps}
monitor_speed = 115200
extra_scripts = 
	${env.extra_scripts}
custom_core_firmware_version = ${env_KeypadVA.custom_core_firmware_version}
custom_community_project = ${env_KeypadVA.custom_community_project}
custom_source_folder = ${env_KeypadVA.custom_source_folder}
custom_zip_filename = ${env_KeypadVA.custom_zip_filename}

[env:feurer_keypadva_nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_flags = 
	${env_KeypadVA.build_flags}
	'-DMOBIFLIGHT_TYPE="Feurer KeypadVA Nano"'
	'-DMOBIFLIGHT_NAME="Feurer KeypadVA"'
	-DMEMLEN_CONFIG=286
	-DMEMLEN_NAMES_BUFFER=220
	-DMF_MAX_DEVICEMEM=420
build_unflags = 
build_src_filter = 
	${env.build_src_filter}
	${env_KeypadVA.build_src_filter}
lib_deps = 
	${env.lib_deps}
	${env.custom_lib_deps_Atmel}
	${env_KeypadVA.lib_deps}
monitor_speed = 115200
extra_scripts = 
	${env.extra_scripts}
custom_core_firmware_version = ${env_KeypadVA.custom_core_firmware_version}
custom_community_project = ${env_KeypadVA.custom_community_project}
custom_source_folder = ${env_KeypadVA.custom_source_folder}
custom_zip_filename = ${env_KeypadVA.custom_zip_filename}

[env:feurer_keypadva_raspberrypico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0M
lib_ldf_mode = chain+
upload_protocol = mbed
build_flags = 
	${env_KeypadVA.build_flags}
	'-DMOBIFLIGHT_TYPE="Feurer KeypadVA RaspiPico"'
	'-DMOBIFLIGHT_NAME="Feurer KeypadVA"'
	-DMEMLEN_CONFIG=1496
	-DMEMLEN_NAMES_BUFFER=1000
	-DMF_MAX_DEVICEMEM=1000
build_unflags = 
build_src_filter = 
	${env.build_src_filter}
	${env_KeypadVA.build_src_filter}
lib_deps = 
	${env.lib_deps}
	${env_KeypadVA.lib_deps}
	${env.custom_lib_deps_Pico}
	chris--a/Keypad@^3.1.1
monitor_speed = 115200
extra_scripts = 
	${env.extra_scripts}
custom_core_firmware_version = ${env_KeypadVA.custom_core_firmware_version}
custom_community_project = ${env_KeypadVA.custom_community_project}
custom_source_folder = ${env_KeypadVA.custom_source_folder}
custom_zip_filename = ${env_KeypadVA.custom_zip_filename}
